blank_issues_enabled: false
contact_links:
  - name: Report an issue
    url: https://github.com/wso2/docs-open-banking/issues/new?labels=cds-toolkit
    about: Click 'Open' to continue. You will be creating the new issue in the 'wso2/docs-open-banking' repo.